# Generated by Django 3.1.6 on 2021-10-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='static/uploads')),
                ('image2', models.ImageField(upload_to='static/uploads')),
                ('image3', models.ImageField(upload_to='static/uploads')),
                ('catagory', models.CharField(choices=[('s', 'sunglass'), ('f', 'frame'), ('e', 'eyelens'), ('m', 'male'), ('f', 'female')], max_length=2)),
            ],
        ),
    ]
