# Generated by Django 3.1.6 on 2021-10-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chasma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
