# Generated by Django 3.1.6 on 2021-10-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chasma', '0002_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discount_price',
        ),
    ]
