# Generated by Django 3.1.6 on 2021-11-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chasma', '0006_auto_20211101_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='produt',
            new_name='product',
        ),
    ]
