# Generated by Django 3.1.6 on 2021-11-03 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chasma', '0011_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked',
            field=models.ManyToManyField(blank=True, default=False, null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
