# Generated by Django 3.1.6 on 2021-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chasma', '0012_product_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='like',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10),
        ),
    ]
