# Generated by Django 3.1.6 on 2021-11-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chasma', '0013_auto_20211103_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
